openapi: 3.0.1
info:
  title: HNTAS.Core.Api | HNTAS.Core.Api
  version: 1.0.0
servers:
- url: https://localhost:7117/
tags:
- name: HeatNetworks
- name: Users
paths:
  /api/HeatNetworks:
    get:
      responses:
        "200":
          content:
            text/plain:
              schema:
                items:
                  $ref: "#/components/schemas/HeatNetwork"
                type: array
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/HeatNetwork"
                type: array
            text/json:
              schema:
                items:
                  $ref: "#/components/schemas/HeatNetwork"
                type: array
          description: OK
        "500":
          description: Internal Server Error
      tags:
      - HeatNetworks
  /api/HeatNetworks/hnIds:
    get:
      parameters:
      - explode: true
        in: query
        name: hnIdsString
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            text/plain:
              schema:
                items:
                  $ref: "#/components/schemas/HeatNetwork"
                type: array
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/HeatNetwork"
                type: array
            text/json:
              schema:
                items:
                  $ref: "#/components/schemas/HeatNetwork"
                type: array
          description: OK
        "400":
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
            text/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
          description: Bad Request
        "404":
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
            text/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
          description: Not Found
        "500":
          description: Internal Server Error
      tags:
      - HeatNetworks
  /api/HeatNetworks/add-heat-network:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/HeatNetwork"
          application/*+json:
            schema:
              $ref: "#/components/schemas/HeatNetwork"
        required: true
      responses:
        "201":
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/HeatNetwork"
            application/json:
              schema:
                $ref: "#/components/schemas/HeatNetwork"
            text/json:
              schema:
                $ref: "#/components/schemas/HeatNetwork"
          description: Created
        "200":
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/HeatNetwork"
            application/json:
              schema:
                $ref: "#/components/schemas/HeatNetwork"
            text/json:
              schema:
                $ref: "#/components/schemas/HeatNetwork"
          description: OK
        "400":
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
            text/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
          description: Bad Request
        "409":
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
            text/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
          description: Conflict
        "500":
          description: Internal Server Error
      tags:
      - HeatNetworks
  /api/Users:
    get:
      responses:
        "200":
          content:
            text/plain:
              schema:
                items:
                  $ref: "#/components/schemas/UserResponse"
                type: array
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/UserResponse"
                type: array
            text/json:
              schema:
                items:
                  $ref: "#/components/schemas/UserResponse"
                type: array
          description: OK
        "500":
          description: Internal Server Error
      tags:
      - Users
  /api/Users/user-details-by-id:
    get:
      parameters:
      - explode: true
        in: query
        name: id
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/UserDetailsResponse"
            application/json:
              schema:
                $ref: "#/components/schemas/UserDetailsResponse"
            text/json:
              schema:
                $ref: "#/components/schemas/UserDetailsResponse"
          description: OK
        "500":
          description: Internal Server Error
      tags:
      - Users
  /api/Users/{id}:
    delete:
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "204":
          description: No Content
        "404":
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
            text/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
          description: Not Found
        "500":
          description: Internal Server Error
      tags:
      - Users
    get:
      operationId: GetUserById
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          maxLength: 24
          minLength: 24
          type: string
        style: simple
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/UserResponse"
            application/json:
              schema:
                $ref: "#/components/schemas/UserResponse"
            text/json:
              schema:
                $ref: "#/components/schemas/UserResponse"
          description: OK
        "404":
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
            text/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
          description: Not Found
        "500":
          description: Internal Server Error
      tags:
      - Users
  /api/Users/onelogin/{oneLoginId}:
    get:
      operationId: GetUserByOneLoginId
      parameters:
      - explode: false
        in: path
        name: oneLoginId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/UserResponse"
            application/json:
              schema:
                $ref: "#/components/schemas/UserResponse"
            text/json:
              schema:
                $ref: "#/components/schemas/UserResponse"
          description: OK
        "404":
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
            text/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
          description: Not Found
        "500":
          description: Internal Server Error
      tags:
      - Users
  /api/Users/initial-entry:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/InitialUserRegistrationRequest"
          application/*+json:
            schema:
              $ref: "#/components/schemas/InitialUserRegistrationRequest"
        required: true
      responses:
        "201":
          content:
            text/plain:
              schema:
                type: string
            application/json:
              schema:
                type: string
            text/json:
              schema:
                type: string
          description: Created
        "400":
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
            text/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
          description: Bad Request
        "409":
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
            text/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
          description: Conflict
        "500":
          description: Internal Server Error
      tags:
      - Users
  /api/Users/{id}/org-details:
    patch:
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          maxLength: 24
          minLength: 24
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateUserOrganisationRequest"
          application/*+json:
            schema:
              $ref: "#/components/schemas/UpdateUserOrganisationRequest"
        required: true
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/User"
            application/json:
              schema:
                $ref: "#/components/schemas/User"
            text/json:
              schema:
                $ref: "#/components/schemas/User"
          description: OK
        "400":
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
            text/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
          description: Bad Request
        "404":
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
            text/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
          description: Not Found
        "500":
          description: Internal Server Error
      tags:
      - Users
  /api/Users/{id}/Invitation:
    patch:
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          maxLength: 24
          minLength: 24
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateInvitationRequest"
          application/*+json:
            schema:
              $ref: "#/components/schemas/UpdateInvitationRequest"
        required: true
      responses:
        "204":
          description: No Content
        "404":
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
            text/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
          description: Not Found
        "500":
          description: Internal Server Error
      tags:
      - Users
  /api/Users/contributor-roles:
    get:
      responses:
        "200":
          content:
            text/plain:
              schema:
                items:
                  $ref: "#/components/schemas/EnumItemResponse"
                type: array
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/EnumItemResponse"
                type: array
            text/json:
              schema:
                items:
                  $ref: "#/components/schemas/EnumItemResponse"
                type: array
          description: OK
      tags:
      - Users
  /api/Users/{id}/heatnetwork/{heatNetworkId}:
    patch:
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          maxLength: 24
          minLength: 24
          type: string
        style: simple
      - explode: false
        in: path
        name: heatNetworkId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "204":
          description: No Content
        "404":
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
            text/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
          description: Not Found
        "500":
          description: Internal Server Error
      tags:
      - Users
  /api/Users/organisation/exists:
    get:
      parameters:
      - explode: true
        in: query
        name: companiesHouseNumber
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: boolean
            application/json:
              schema:
                type: boolean
            text/json:
              schema:
                type: boolean
          description: OK
        "400":
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
            text/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
          description: Bad Request
        "500":
          description: Internal Server Error
      tags:
      - Users
  /api/Users/managed-users:
    get:
      parameters:
      - explode: true
        in: query
        name: userId
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ManagedUserResponse"
          description: OK
        "404":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
          description: Not Found
      tags:
      - Users
components:
  schemas:
    ContributorRole:
      enum:
      - DesignatedDesigner
      - DesignatedContractor
      - DesignatedOperator
      type: string
    EnumItemResponse:
      example:
        name: name
        description: description
        value: 0
      properties:
        value:
          format: int32
          type: integer
        name:
          type: string
        description:
          type: string
      type: object
    HeatNetwork:
      example:
        hnId: hnId
        name: name
        location: location
        id: id
      properties:
        id:
          nullable: true
          type: string
        hnId:
          nullable: true
          type: string
        location:
          type: string
        name:
          type: string
      type: object
    HeatNetworkResponse:
      example:
        hnId: hnId
        name: name
        location: location
      properties:
        hnId:
          type: string
        name:
          type: string
        location:
          type: string
      type: object
    InitialUserRegistrationRequest:
      example:
        oneLoginId: oneLoginId
        emailId: emailId
        status: Active
      properties:
        oneLoginId:
          type: string
        emailId:
          type: string
        status:
          $ref: "#/components/schemas/UserStatus"
      required:
      - emailId
      - oneLoginId
      - status
      type: object
    InvitationStatus:
      enum:
      - Invited
      - Accepted
      - Rejected
      type: string
    InvitedUserResponse:
      example:
        firstName: firstName
        lastName: lastName
        rejectedAt: 2000-01-23T04:56:07.000+00:00
        roles:
        - roles
        - roles
        fullName: fullName
        id: id
        email: email
        status: status
        invitedAt: 2000-01-23T04:56:07.000+00:00
        acceptedAt: 2000-01-23T04:56:07.000+00:00
      properties:
        id:
          type: string
        email:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        fullName:
          nullable: true
          type: string
        roles:
          items:
            type: string
          type: array
        status:
          type: string
        invitedAt:
          format: date-time
          type: string
        acceptedAt:
          format: date-time
          nullable: true
          type: string
        rejectedAt:
          format: date-time
          nullable: true
          type: string
      type: object
    ManagedUserResponse:
      example:
        responsibleUser:
          lastName: lastName
          preferredContactType: preferredContactType
          mobileNumber: mobileNumber
          jobTitle: jobTitle
          roles:
          - roles
          - roles
          oneLoginId: oneLoginId
          fullName: fullName
          emailId: emailId
          landlineNumber: landlineNumber
          orgId: orgId
          firstName: firstName
          id: id
          hnIds:
          - hnIds
          - hnIds
          status: status
        registeredUsers:
        - lastName: lastName
          preferredContactType: preferredContactType
          mobileNumber: mobileNumber
          jobTitle: jobTitle
          roles:
          - roles
          - roles
          oneLoginId: oneLoginId
          fullName: fullName
          emailId: emailId
          landlineNumber: landlineNumber
          orgId: orgId
          firstName: firstName
          id: id
          hnIds:
          - hnIds
          - hnIds
          status: status
        - lastName: lastName
          preferredContactType: preferredContactType
          mobileNumber: mobileNumber
          jobTitle: jobTitle
          roles:
          - roles
          - roles
          oneLoginId: oneLoginId
          fullName: fullName
          emailId: emailId
          landlineNumber: landlineNumber
          orgId: orgId
          firstName: firstName
          id: id
          hnIds:
          - hnIds
          - hnIds
          status: status
        invitedUsers:
        - firstName: firstName
          lastName: lastName
          rejectedAt: 2000-01-23T04:56:07.000+00:00
          roles:
          - roles
          - roles
          fullName: fullName
          id: id
          email: email
          status: status
          invitedAt: 2000-01-23T04:56:07.000+00:00
          acceptedAt: 2000-01-23T04:56:07.000+00:00
        - firstName: firstName
          lastName: lastName
          rejectedAt: 2000-01-23T04:56:07.000+00:00
          roles:
          - roles
          - roles
          fullName: fullName
          id: id
          email: email
          status: status
          invitedAt: 2000-01-23T04:56:07.000+00:00
          acceptedAt: 2000-01-23T04:56:07.000+00:00
      properties:
        responsibleUser:
          $ref: "#/components/schemas/UserResponse"
        registeredUsers:
          items:
            $ref: "#/components/schemas/UserResponse"
          type: array
        invitedUsers:
          items:
            $ref: "#/components/schemas/InvitedUserResponse"
          type: array
      type: object
    NullableOfPreferredContactType:
      enum:
      - Landline
      - Mobile
      - null
      nullable: true
      type: string
    OrganisationRequest:
      example:
        registeredAddress:
          country: country
          town: town
          county: county
          postcode: postcode
          addressLine1: addressLine1
          addressLine2: addressLine2
        name: name
        type: UkCompaniesHouse
        companiesHouseNumber: companiesHouseNumber
      properties:
        name:
          type: string
        companiesHouseNumber:
          nullable: true
          type: string
        type:
          $ref: "#/components/schemas/OrganisationType"
        registeredAddress:
          $ref: "#/components/schemas/RegisteredAddress"
      required:
      - name
      - registeredAddress
      - type
      type: object
    OrganisationResponse:
      example:
        registeredAddress:
          country: country
          town: town
          county: county
          postcode: postcode
          addressLine1: addressLine1
          addressLine2: addressLine2
        name: name
        type: type
        companiesHouseNumber: companiesHouseNumber
        orgId: orgId
      nullable: true
      properties:
        orgId:
          type: string
        name:
          type: string
        companiesHouseNumber:
          nullable: true
          type: string
        type:
          type: string
        registeredAddress:
          $ref: "#/components/schemas/RegisteredAddress"
      type: object
    OrganisationType:
      enum:
      - UkCompaniesHouse
      - OtherUkOrganisation
      - OverseasOrganisation
      type: string
    PreferredContactType:
      enum:
      - Landline
      - Mobile
      type: string
    ProblemDetails:
      example:
        instance: instance
        detail: detail
        type: type
        title: title
        status: 0
      properties:
        type:
          nullable: true
          type: string
        title:
          nullable: true
          type: string
        status:
          format: int32
          nullable: true
          type: integer
        detail:
          nullable: true
          type: string
        instance:
          nullable: true
          type: string
      type: object
    RegisteredAddress:
      example:
        country: country
        town: town
        county: county
        postcode: postcode
        addressLine1: addressLine1
        addressLine2: addressLine2
      properties:
        addressLine1:
          type: string
        addressLine2:
          nullable: true
          type: string
        town:
          nullable: true
          type: string
        county:
          nullable: true
          type: string
        postcode:
          type: string
        country:
          nullable: true
          type: string
      required:
      - addressLine1
      - postcode
      type: object
    UpdateInvitationRequest:
      example:
        firstName: firstName
        lastName: lastName
        hnId: hnId
        emailAddress: emailAddress
        contributorRoles:
        - DesignatedDesigner
        - DesignatedDesigner
        preferredContactType: Landline
        mobileNumber: mobileNumber
        landlineNumber: landlineNumber
        contactNumberExtension: contactNumberExtension
        status: Invited
      properties:
        emailAddress:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        preferredContactType:
          $ref: "#/components/schemas/PreferredContactType"
        landlineNumber:
          maxLength: 20
          nullable: true
          pattern: "^\\+?\\d{1,3}[\\s-]?\\(?\\d{1,4}\\)?[\\s-]?\\d{1,4}[\\s-]?\\d{1,4}[\\\
            s-]?\\d{1,9}$"
          type: string
        mobileNumber:
          maxLength: 13
          nullable: true
          pattern: "^\\+?\\d{1,3}[\\s-]?\\(?\\d{1,4}\\)?[\\s-]?\\d{1,4}[\\s-]?\\d{1,4}[\\\
            s-]?\\d{1,9}$"
          type: string
        contactNumberExtension:
          maxLength: 10
          nullable: true
          pattern: ^\d*$
          type: string
        hnId:
          type: string
        contributorRoles:
          items:
            $ref: "#/components/schemas/ContributorRole"
          minItems: 1
          type: array
        status:
          $ref: "#/components/schemas/InvitationStatus"
      required:
      - contributorRoles
      - emailAddress
      - firstName
      - hnId
      - lastName
      - preferredContactType
      - status
      type: object
    UpdateUserOrganisationRequest:
      example:
        firstName: firstName
        lastName: lastName
        role: RegulatoryContact
        preferredContactType: Landline
        mobileNumber: mobileNumber
        jobTitle: jobTitle
        organisation:
          registeredAddress:
            country: country
            town: town
            county: county
            postcode: postcode
            addressLine1: addressLine1
            addressLine2: addressLine2
          name: name
          type: UkCompaniesHouse
          companiesHouseNumber: companiesHouseNumber
        landlineNumber: landlineNumber
        contactNumberExtension: contactNumberExtension
      properties:
        firstName:
          type: string
        lastName:
          type: string
        preferredContactType:
          $ref: "#/components/schemas/PreferredContactType"
        landlineNumber:
          nullable: true
          type: string
        contactNumberExtension:
          nullable: true
          type: string
        mobileNumber:
          nullable: true
          type: string
        jobTitle:
          type: string
        role:
          $ref: "#/components/schemas/UserRole"
        organisation:
          $ref: "#/components/schemas/OrganisationRequest"
      required:
      - firstName
      - jobTitle
      - lastName
      - organisation
      - preferredContactType
      - role
      type: object
    User:
      example:
        lastName: lastName
        preferredContactType: Landline
        mobileNumber: mobileNumber
        jobTitle: jobTitle
        roles:
        - RegulatoryContact
        - RegulatoryContact
        oneLoginId: oneLoginId
        emailId: emailId
        landlineNumber: landlineNumber
        orgId: orgId
        firstName: firstName
        id: id
        hnIds:
        - hnIds
        - hnIds
        status: Active
      properties:
        id:
          nullable: true
          type: string
        oneLoginId:
          type: string
        orgId:
          nullable: true
          type: string
        firstName:
          nullable: true
          type: string
        lastName:
          nullable: true
          type: string
        jobTitle:
          nullable: true
          type: string
        emailId:
          type: string
        preferredContactType:
          $ref: "#/components/schemas/NullableOfPreferredContactType"
        landlineNumber:
          nullable: true
          type: string
        mobileNumber:
          nullable: true
          type: string
        hnIds:
          items:
            type: string
          nullable: true
          type: array
        roles:
          items:
            $ref: "#/components/schemas/UserRole"
          nullable: true
          type: array
        status:
          $ref: "#/components/schemas/UserStatus"
      type: object
    UserDetailsResponse:
      example:
        lastName: lastName
        preferredContactType: preferredContactType
        mobileNumber: mobileNumber
        jobTitle: jobTitle
        roles:
        - roles
        - roles
        oneLoginId: oneLoginId
        fullName: fullName
        organisation:
          registeredAddress:
            country: country
            town: town
            county: county
            postcode: postcode
            addressLine1: addressLine1
            addressLine2: addressLine2
          name: name
          type: type
          companiesHouseNumber: companiesHouseNumber
          orgId: orgId
        emailId: emailId
        landlineNumber: landlineNumber
        firstName: firstName
        heatNetworks:
        - hnId: hnId
          name: name
          location: location
        - hnId: hnId
          name: name
          location: location
        id: id
        status: status
      properties:
        id:
          type: string
        oneLoginId:
          type: string
        firstName:
          nullable: true
          type: string
        lastName:
          nullable: true
          type: string
        fullName:
          nullable: true
          type: string
        emailId:
          type: string
        jobTitle:
          nullable: true
          type: string
        preferredContactType:
          nullable: true
          type: string
        landlineNumber:
          nullable: true
          type: string
        mobileNumber:
          nullable: true
          type: string
        status:
          type: string
        roles:
          items:
            type: string
          nullable: true
          type: array
        organisation:
          $ref: "#/components/schemas/OrganisationResponse"
        heatNetworks:
          items:
            $ref: "#/components/schemas/HeatNetworkResponse"
          nullable: true
          type: array
      type: object
    UserResponse:
      example:
        lastName: lastName
        preferredContactType: preferredContactType
        mobileNumber: mobileNumber
        jobTitle: jobTitle
        roles:
        - roles
        - roles
        oneLoginId: oneLoginId
        fullName: fullName
        emailId: emailId
        landlineNumber: landlineNumber
        orgId: orgId
        firstName: firstName
        id: id
        hnIds:
        - hnIds
        - hnIds
        status: status
      properties:
        id:
          type: string
        oneLoginId:
          type: string
        emailId:
          type: string
        firstName:
          nullable: true
          type: string
        lastName:
          nullable: true
          type: string
        fullName:
          nullable: true
          type: string
        jobTitle:
          type: string
        preferredContactType:
          nullable: true
          type: string
        landlineNumber:
          nullable: true
          type: string
        mobileNumber:
          nullable: true
          type: string
        orgId:
          nullable: true
          type: string
        roles:
          items:
            type: string
          nullable: true
          type: array
        status:
          type: string
        hnIds:
          items:
            type: string
          nullable: true
          type: array
      type: object
    UserRole:
      enum:
      - RegulatoryContact
      - ThirdParty
      - Contributor
      type: string
    UserStatus:
      enum:
      - Active
      - InActive
      - InvitationSent
      - InvitationAccepted
      - InvitationDeclined
      type: string

